spring:
  datasource:
    url: jdbc:h2:file:./db/quartz_sandbox
    driverClassName: org.h2.Driver
    username: sandbox
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

